###############
## 
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'LLIE'
 
# Optimization arguments.
OPTIM:
  BATCH_SIZE: 8
  NUM_EPOCHS: 500
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 5
  RESUME: True
  TRAIN_PS: 128
  VAL_PS: 128
  TRAIN_DIR: '       # path to training data
  VAL_DIR: ' # path to validation data
  SAVE_DIR: '         # path to save models and images
  # SAVE_IMAGES: False
